---
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "./tests/setup"
    schedule:
      interval: "weekly"

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "./tests/testsuite/roles/testing/files"
    schedule:
      interval: "weekly"
