[mysqld]
user = "mysql"
server_id = "${SERVER_ID}"
disabled_storage_engines = "MyISAM,BLACKHOLE,FEDERATED,ARCHIVE,MEMORY"
performance_schema = "ON"
transaction_isolation = "READ-COMMITTED"
binlog_transaction_dependency_tracking = "WRITESET"
enforce_gtid_consistency = "ON"
gtid_mode = "ON"
pid-file = "/var/run/mysqld/mysqld.pid"
ssl-ca = "/etc/mysql/ssl/superset_cluster_ca_certificate.pem"
ssl-cert = "/etc/mysql/ssl/mysql_server_certificate.pem"
ssl-key = "/etc/mysql/ssl/mysql_server_key.pem"
require_secure_transport = "ON"
max_connections = "50"
max_connect_errors = "50"
