[mysqld]
server_id=${SERVER_ID}
disabled_storage_engines="MyISAM,BLACKHOLE,FEDERATED,ARCHIVE,MEMORY"
performance_schema=ON
transaction_isolation=READ-COMMITTED
default_authentication_plugin=mysql_native_password
binlog_transaction_dependency_tracking=WRITESET
