#!/usr/bin/expect -f

log_user 0

set timeout 10
set mysql_root_password [exec cat "/var/run/mysqld/mysql_root_password"]
set filepath $env(MYSQL_TEST_LOGIN_FILE)

foreach node $argv {
    spawn mysql_config_editor set \
        --login-path=$node \
        --host=$node \
        --user=root \
        --skip-warn \
        --password

    expect "Enter password:"
    send "$mysql_root_password\r"
}

expect eof

set base64_encoded [exec base64 $filepath]

puts $base64_encoded
