---
services:
  initcontainer:
    build: "."
    image: "mysql-mgmt"
    user: "root"
    entrypoint: [ "/opt/entrypoint.sh" ]
    container_name: "mysql-mgmt-initcontainer"
    network_mode: "host"
    restart: "no"
    environment:
      IS_PRIMARY_MGMT_NODE: "${IS_PRIMARY_MGMT_NODE}"
      VIRTUAL_IP_ADDRESS: "${VIRTUAL_IP_ADDRESS}"
      VIRTUAL_NETWORK_INTERFACE: "${VIRTUAL_NETWORK_INTERFACE}"
      PRIMARY_MYSQL_NODE: "${PRIMARY_MYSQL_NODE}"
      SECONDARY_FIRST_MYSQL_NODE: "${SECONDARY_FIRST_MYSQL_NODE}"
      SECONDARY_SECOND_MYSQL_NODE: "${SECONDARY_SECOND_MYSQL_NODE}"
      MYSQL_TEST_LOGIN_FILE: "/opt/.mylogin.cnf"
    volumes:
      - "initcontainer_generated:/opt/initcontainer"

  maincontainer:
    image: "mysql-mgmt"
    user: "superset"
    entrypoint:
      - "sh"
      - "-c"
      - |
        sudo keepalived --use-file /opt/initcontainer/keepalived.conf \
        && mysqlrouter --config /opt/initcontainer/mysql_router/mysqlrouter.conf
    container_name: "mysql-mgmt"
    restart: "always"
    hostname: "${HOSTNAME}"
    network_mode: "host"
    cap_add:
      - "NET_ADMIN"
    volumes:
      - "initcontainer_generated:/opt/initcontainer"

volumes:
  initcontainer_generated:
