---
services:
  initcontainer:
    build: "."
    image: "mysql-mgmt"
    user: "root"
    container_name: "mysql-mgmt-initcontainer"
    network_mode: "host"
    restart: "no"
    entrypoint:
      - "/bin/bash"
      - "-c"
      - |
        set -euo pipefail
        if [ "${IS_PRIMARY_MGMT_NODE}" = "true" ]; then
          export STATE="MASTER"
          export PRIORITY="100"
          mysqlsh --login-path="${PRIMARY_MYSQL_NODE}" --execute="dba.configureInstance('${PRIMARY_MYSQL_NODE}')"
          mysqlsh --login-path="${SECONDARY_FIRST_MYSQL_NODE}" --execute="dba.configureInstance('${SECONDARY_FIRST_MYSQL_NODE}')"
          mysqlsh --login-path="${SECONDARY_SECOND_MYSQL_NODE}" --execute="dba.configureInstance('${SECONDARY_SECOND_MYSQL_NODE}')"          
          mysqlsh --login-path="${PRIMARY_MYSQL_NODE}" --execute="dba.createCluster('superset');"
          mysqlsh --login-path="${SECONDARY_FIRST_MYSQL_NODE}" --sql --execute="RESET MASTER;"
          mysqlsh --login-path="${PRIMARY_MYSQL_NODE}" --execute="dba.getCluster('superset').addInstance('${SECONDARY_FIRST_MYSQL_NODE}',{recoveryMethod:'incremental'});"
          mysqlsh --login-path="${SECONDARY_SECOND_MYSQL_NODE}" --sql --execute="RESET MASTER;"
          mysqlsh --login-path="${PRIMARY_MYSQL_NODE}" --execute="dba.getCluster('superset').addInstance('${SECONDARY_SECOND_MYSQL_NODE}',{recoveryMethod:'incremental'});"
          /opt/envsubst-Linux-x86_64 < "/opt/superset-user.sql.tpl" > "/opt/superset-user.sql"
          mysqlsh --login-path="${PRIMARY_MYSQL_NODE}" --sql --file="/opt/superset-user.sql"
        else
          export STATE="BACKUP"
          export PRIORITY="90"
        fi
        ifmetric ${VIRTUAL_NETWORK_INTERFACE} 2
        /opt/envsubst-Linux-x86_64 < "/opt/keepalived.conf.tpl" > "/opt/default/keepalived.conf";
        chown superset:superset "/opt/default"
    cap_add:
      - "NET_ADMIN"
    env_file:
      - "/opt/superset-cluster/mysql-mgmt/.env-initcontainer"
    volumes:
      - "default_generated:/opt/default"

  maincontainer:
    image: "mysql-mgmt"
    user: "superset"
    entrypoint:
      - "/bin/bash"
      - "-c"
      - |
        set -euo pipefail
        ip monitor dev "${VIRTUAL_NETWORK_INTERFACE}" > "/opt/default/ifstatus" &
        sudo keepalived --use-file "/opt/default/keepalived.conf"
        timeout ${HEALTHCHECK_START_PERIOD} watch --chgexit --interval 1 "stat /opt/default/ifstatus" > /dev/null 2>&1
        &&
        if [ ! -d "/opt/default/mysql_router/" ]; then
          mysqlrouter --user "superset" --bootstrap "superset:cluster@${PRIMARY_MYSQL_NODE}:3306" --directory "/opt/default/mysql_router" --conf-use-sockets
        fi
        mysqlrouter --config "/opt/default/mysql_router/mysqlrouter.conf"
    container_name: "mysql-mgmt"
    restart: "always"
    hostname: "${HOSTNAME}"
    network_mode: "host"
    cap_add:
      - "NET_ADMIN"
    volumes:
      - "default_generated:/opt/default"

volumes:
  default_generated:

    # env_file:
    #   - "/opt/superset-cluster/mysql-mgmt/.env-maincontainer"