---
services:
  initcontainer:
    build: "."
    image: "mysql-mgmt"
    user: "root"
    container_name: "mysql-mgmt-initcontainer"
    network_mode: "host"
    restart: "no"
    entrypoint:
      - "/bin/bash"
      - "-c"
      - |
        set -euo pipefail
        export VIRTUAL_IP_ADDRESS="${VIRTUAL_IP_ADDRESS}"
        export VIRTUAL_IP_ADDRESS_MASK="${VIRTUAL_IP_ADDRESS_MASK}"
        export VIRTUAL_NETWORK_INTERFACE="${VIRTUAL_NETWORK_INTERFACE}"
        export VIRTUAL_NETWORK="${VIRTUAL_NETWORK}"
        export MYSQL_TEST_LOGIN_FILE="/opt/.mylogin.cnf"
        mv "/opt/superset_cluster_ca_certificate.pem" "/opt/default/superset_cluster_ca_certificate.pem"
        mv "/opt/mysql_router_${MGMT_NODE_TYPE}_certificate.pem" "/opt/default/mysql_router_${MGMT_NODE_TYPE}_certificate.pem"
        mv "/opt/mysql_router_${MGMT_NODE_TYPE}_key.pem" "/opt/default/mysql_router_${MGMT_NODE_TYPE}_key.pem"
        if [ "${MGMT_NODE_TYPE}" = "primary" ]; then
          export STATE="MASTER"
          export PRIORITY="100"
          export NODE_IP_ADDRESS=$(ip -oneline -4 addr show ${VIRTUAL_NETWORK_INTERFACE} | awk '{print $4}' | cut --delimiter=/ --fields=1 | head --lines=1)
          mysqlsh --login-path="${PRIMARY_MYSQL_NODE}" --execute="dba.configureInstance('${PRIMARY_MYSQL_NODE}')"
          mysqlsh --login-path="${SECONDARY_FIRST_MYSQL_NODE}" --execute="dba.configureInstance('${SECONDARY_FIRST_MYSQL_NODE}')"
          mysqlsh --login-path="${SECONDARY_SECOND_MYSQL_NODE}" --execute="dba.configureInstance('${SECONDARY_SECOND_MYSQL_NODE}')"
          mysqlsh --login-path="${PRIMARY_MYSQL_NODE}" --execute="dba.createCluster('superset');"
          mysqlsh --login-path="${SECONDARY_FIRST_MYSQL_NODE}" --sql --execute="RESET MASTER;"
          mysqlsh --login-path="${PRIMARY_MYSQL_NODE}" --execute="dba.getCluster('superset').addInstance('${SECONDARY_FIRST_MYSQL_NODE}',{recoveryMethod:'incremental'});"
          mysqlsh --login-path="${SECONDARY_SECOND_MYSQL_NODE}" --sql --execute="RESET MASTER;"
          mysqlsh --login-path="${PRIMARY_MYSQL_NODE}" --execute="dba.getCluster('superset').addInstance('${SECONDARY_SECOND_MYSQL_NODE}',{recoveryMethod:'incremental'});"
          /opt/envsubst-Linux-x86_64 < "/opt/superset-user.sql.tpl" > "/opt/superset-user.sql"
          mysqlsh --login-path="${PRIMARY_MYSQL_NODE}" --sql --file="/opt/superset-user.sql"
          mysqlrouter --user "superset" --bootstrap "superset:cluster@${PRIMARY_MYSQL_NODE}:3306" --directory "/opt/default/mysql_router" --conf-use-sockets --client-ssl-mode="REQUIRED" --server-ssl-mode="REQUIRED" --ssl-ca="/opt/default/superset_cluster_ca_certificate.pem" --client-ssl-cert="/opt/default/mysql_router_${MGMT_NODE_TYPE}_certificate.pem" --client-ssl-key="/opt/default/mysql_router_${MGMT_NODE_TYPE}_key.pem"
          mysqlsh --login-path="${PRIMARY_MYSQL_NODE}" --sql --execute="DROP USER 'superset'@'$(ip -oneline -4 addr show ${VIRTUAL_NETWORK_INTERFACE} | awk '{print $4}' | cut --delimiter=/ --fields=1 | head --lines=1)';"
          export NODE_IP_ADDRESS=${VIRTUAL_IP_ADDRESS}
          mysqlsh --login-path="${PRIMARY_MYSQL_NODE}" --sql --file="/opt/superset-user.sql"
        else
          export STATE="BACKUP"
          export PRIORITY="90"
          export NODE_IP_ADDRESS=$(ip -oneline -4 addr show ${VIRTUAL_NETWORK_INTERFACE} | awk '{print $4}' | cut --delimiter=/ --fields=1 | head --lines=1)
          /opt/envsubst-Linux-x86_64 < "/opt/superset-user.sql.tpl" > "/opt/superset-user.sql"
          mysqlsh --login-path="${PRIMARY_MYSQL_NODE}" --sql --file="/opt/superset-user.sql"
          mysqlrouter --user "superset" --bootstrap "superset:cluster@${PRIMARY_MYSQL_NODE}:3306" --directory "/opt/default/mysql_router" --conf-use-sockets --client-ssl-mode="REQUIRED" --server-ssl-mode="REQUIRED" --ssl-ca="/opt/default/superset_cluster_ca_certificate.pem" --client-ssl-cert="/opt/default/mysql_router_${MGMT_NODE_TYPE}_certificate.pem" --client-ssl-key="/opt/default/mysql_router_${MGMT_NODE_TYPE}_key.pem"
          mysqlsh --login-path="${PRIMARY_MYSQL_NODE}" --sql --execute="DROP USER 'superset'@'$(ip -oneline -4 addr show ${VIRTUAL_NETWORK_INTERFACE} | awk '{print $4}' | cut --delimiter=/ --fields=1 | head --lines=1)';"
        fi
        ifmetric ${VIRTUAL_NETWORK_INTERFACE} 2
        /opt/envsubst-Linux-x86_64 < "/opt/keepalived.conf.tpl" > "/opt/default/keepalived.conf";
        chown --recursive superset:superset "/opt/default"
    cap_add:
      - "NET_ADMIN"
    volumes:
      - "default_generated:/opt/default"

  maincontainer:
    image: "mysql-mgmt"
    user: "superset"
    entrypoint:
      - "/bin/bash"
      - "-c"
      - |
        set -euo pipefail
        sudo keepalived --use-file "/opt/default/keepalived.conf"
        sleep ${HEALTHCHECK_START_PERIOD}
        mysqlrouter --config "/opt/default/mysql_router/mysqlrouter.conf"
    container_name: "mysql-mgmt"
    restart: "always"
    hostname: "${HOSTNAME}"
    network_mode: "host"
    cap_add:
      - "NET_ADMIN"
    volumes:
      - "default_generated:/opt/default"

volumes:
  default_generated:
