---
services:
  initcontainer:
    build: "."
    image: "mysql-mgmt"
    user: "root"
    entrypoint: [ "/opt/entrypoint.sh" ]
    container_name: "mysql-mgmt-initcontainer"
    network_mode: "host"
    restart: "no"
    cap_add:
      - "NET_ADMIN"
    environment:
      IS_PRIMARY_MGMT_NODE: "${IS_PRIMARY_MGMT_NODE}"
      VIRTUAL_IP_ADDRESS: "${VIRTUAL_IP_ADDRESS}"
      VIRTUAL_IP_ADDRESS_MASK: "${VIRTUAL_IP_ADDRESS_MASK}"
      VIRTUAL_NETWORK_INTERFACE: "${VIRTUAL_NETWORK_INTERFACE}"
      VIRTUAL_NETWORK: "${VIRTUAL_NETWORK}"
      PRIMARY_MYSQL_NODE: "${PRIMARY_MYSQL_NODE}"
      SECONDARY_FIRST_MYSQL_NODE: "${SECONDARY_FIRST_MYSQL_NODE}"
      SECONDARY_SECOND_MYSQL_NODE: "${SECONDARY_SECOND_MYSQL_NODE}"
      MYSQL_TEST_LOGIN_FILE: "/opt/.mylogin.cnf"
    volumes:
      - "default_generated:/opt/default"

  maincontainer:
    image: "mysql-mgmt"
    user: "superset"
    entrypoint:
      - "bash"
      - "-c"
      - |
        ip monitor dev ${VIRTUAL_NETWORK_INTERFACE} > /opt/default/ifstatus &
        sudo keepalived --use-file "/opt/default/keepalived.conf" \
        && \
        timeout ${HEALTHCHECK_START_PERIOD} bash -c "watch -g -n 1 'stat /opt/default/ifstatus'" \
        && \
        if [ ! -d "/opt/default/mysql_router/" ]; then \
          mysqlrouter --user "superset" --bootstrap "superset:cluster@${PRIMARY_MYSQL_NODE}:3306" --directory "/opt/default/mysql_router" --conf-use-sockets; \
        fi \
        && \
        mysqlrouter --config "/opt/default/mysql_router/mysqlrouter.conf"
    container_name: "mysql-mgmt"
    restart: "always"
    hostname: "${HOSTNAME}"
    network_mode: "host"
    environment:
      PRIMARY_MYSQL_NODE: "${PRIMARY_MYSQL_NODE}"
      VIRTUAL_NETWORK_INTERFACE: "${VIRTUAL_NETWORK_INTERFACE}"
      HEALTHCHECK_START_PERIOD: 20
    cap_add:
      - "NET_ADMIN"
    volumes:
      - "default_generated:/opt/default"

volumes:
  default_generated:
